### ISSUE TITLE
size option

### ISSUE THREAD

**Issue by rchrdnsh** [Tronic247/svelte-ripple-action#1]
let's say I have a giant div, like 1024 x 1024, but I want the ripple inside the div to only be a max of 128px in any direction...a size attr would be sweet for that :-)

**Comment by Posandu** [comment]
That's a nice idea! Will add that

**Comment by Posandu** [comment]
Added in @1.0.3 @rchrdnsh 

```svelte
<button use:ripple={{ maxRadius: 100 }}>100px</button>
```

**Comment by rchrdnsh** [comment]
perfect, works great, thanks :-)
