### ISSUE TITLE
Not working across SvelteKit page changes

### ISSUE THREAD

**Issue by OfficialCRUGG** [Tronic247/svelte-ripple-action#3]
The ripple effect seems to not work across page changes with SvelteKit. When using it on a SvelteKit link, the ripple just plays in the top left of the screen, regardless of where the button is.

**Comment by Posandu** [comment]
Hey @OfficialCRUGG can you provide an example where it happens? I can't seem to reproduce it on https://www.sveltelab.dev/mo9p9we0o1vdrd3

You also can try adding the class `ripple-effect` to the element and see if it happens

**Comment by NatumanyaGuy** [comment]
Hey there, Got the same issue with the ripple behavior on transition from different Sveltekit routes.
Managed to replicate it on a [`SvelteLab` project](https://www.sveltelab.dev/?files=.%2Fsrc%2Froutes%2Fglobal.css#code=N4IgdA5glgLlEDsD2AnApiAXKAZlANhtiAMZIIxoUDOWoA1lAgCZYjUBua%2Bl%2BAhgCMAtAFcoADj4gANCAEicONCiwBtACwA2aZvHTxAZmkBOAKz6jARkvbrl6dfUOADPcvOH7z2%2Bcf39sxdjbxc-SwB2Fz1-T3MvdUjjaIiXOOdo3xdpBOzbSzjLDJ9k21dstMj3AtLsyssAJhNE4PdEyucrMvjSty9rDNyXXrC9LWzGrwMjMZjrEcHZ%2Bo9jdpaGqKGs-tTPHsHjNeGXCec06dK88xmbHfcWrvzdpqDPRvUrk88M6s2xg5C5sdbh0FjdrFc8qU0vdej8Vi9rG8Pi4ALoAXwxsjAAAd0DA4MoUCQ6CA8IQSWQKFQYLRiIwWGxONxeIJRBIpLJ5IplGoGp0TNIDE5rHU0vZxE54UlYoKnKY9AYJmDLMKUjF1MLlrKZVVPH4Qe4ivpenVenshdJ5YKlXlVe17BqssELdZbc9dYbbn0QZpTQjnMF4RarYrtYC7HrNhbHV5naqlZqCmFtOJ2mlky4nMGFW9gupRqNNQKXetPSKXJ0kzLs9aTPYSwnNq6nh6Hk53q8NuX3JXIx3wV8m%2BkW2ULcZpkW452y2qDadI4ZNvDHCZ7k5dF7VeYa6HjPX29oxxOnWHrIPZirPInQk3HjvGnuHPUjKGXc4TmkjQP79r1G9LueXTDs2MTRlmjQlr0Npekc35yjmT4vhB8bupeA4Xlm8G1iWBRfsBYKjuBT7bhM9TmOOWxkaiGJorI2J8CQ9B8BAaBgAAVtQ5AkmSRCgJSlA0CS9KsJg7BcDw3CsmIkgyHIChKComCqHyJ4lssqxRlhr6Snoy6PLq-xgapqpfmh%2BnzhGgI-tGozaPmgzqFOMZag2V5erpdTmlp0Ert2ZTOcWW6rm5Hqlsq27eYhJ5Tu4%2Bq9AqkUlt8I71iccWDkZsaBSYyRpl2mTWSZXrmg%2BuXAhkHiZVqMVhZq8XAr0U4hshgE-KBSqNheyUXk5k7ZWWFl9DchXTmhDyQg1bmhh2-alvh7S9oCs1iqhkpruUN6hURYzTVc5HrTE-ytLWO3tn1MXvgCY2Bp52rNaenXjSOK0rrtG2Il2s6LfEBQrXpa2Zu9mRbSdh5Iu9lhrNeIGjv%2BYZag0Vx9W%2B6XbBuF4nLBwMPMs9wvXekUqVlU6aEF2yzPhezuABOTLpkek%2BW2G16bdEYjcYcoeGM9ncwl2TndqpM6oUQ4lEONPtHlzbs%2B2ebaKYXO2ZaLUBYGD0hU9MP45hloIWOnODKYdl2Xzqv9bVt4Ta2vTtgUJxlT2Xpc79gHFCld165KBvc3mSuOb%2BAs4a7n1ebr2Fe8rDlK6YL5ndFp7dQR%2B5h9pJhynDpgZ5VfWI-zxktvUUGaSnLV3ACwOzkaVX9djRcXvqqOxnjt4RSXUXE6euGi%2B7HZHc4dXBcdMuWg68sZzrZs1V3FNi%2BqBTQ2F9u-ORzTPVd2dt-r2Ry9k0elwjVF9Ifzjopi7BEiSzBQOgJAwKgACeJJ8Ni2JgAAFjAAC2%2BDcQQvGkOQASNIhJMBEmJZkklhDSQ5HJbkilVCaEqkYDc4Rgi%2Bn0E4cQwRxAeE0M6E4qpSj3D0JoT4iDAYw2IbWT0el9TIOTvXQWnw0H6gHnTXBzCBTkLLhebQQYHzrX%2BjqJ6mgGFqgIuDI22ppqRFIfHbhwFBr6kiKGXyQESEMPnEdM8VkiLuFVAPdwjRRHSNFMHGcVNnBSxuH8Mx6FNZ3kiDkIxqFkraKONcJUdDpFvFkZwlh-ozTPFUbGDSMQTFJUmtYNYSobZPAtLuQ4kYYawRuBE1UzdYojnXD4RubiYQQ0yRXUoOsZE6H8YKOxIsZ7u2OqFY2FCyjsMqSechzj%2B5LnaBw1pyxki5KfKlG8ek%2BFOJduTdRtSrHFQho9N2EZmn9nprdeE6SKE6OqUzC0ciO4KP1F3EJbVC75XsKsrJoU7YbGXEc%2B67jklJzuQBLZEEql4VnkBaxDTpSWWBkcgwsiuZdPcuUnptQcrlz8Ec7ZuCAVrKIRsKFp9aIgHwFAAQl9r5oFvg-EkAA5PgHABB8BQGAJkElf7kmIPxaktIGCgMZOJFkUD2SyS5ApNQ3DHjaIXtBKFApWwxKuoQ6hz5qEGnWXkQZudVGXV8jogM2FnQjNGr4yMeluogmGTBSMBhgimHuHyiy8qPqWTMmDKKISHwLSjKREiQJZU%2BHwYKRVqEOqgvQsqOJF5ty6v1UUgVJqhWqJFSE7l05FGSqotKzqcrHU6uFq8nu88vSuoGg6Feg8CIFCOHGvVql5YIUCB9OmnRBkRIgnkS1FZfhuhNazfyUIby5q8G0sxXLk1PF5c2huQLiZUL0i7U5oTBzSiEW%2BYFWVyFTA2h2UM4RYmBOwuDDsvKAl0wFAdMaPhjHJxyGOtW3ZzL2CtGoi5xrw3xz7h5YW5hTmVQgve4VRhC3rGLdanQJzBlxt3Y6zQSEnXPG0Q28Zab8pViHo6%2B6ca4250mA%2B18%2B8uGcLneXApE6YUrM%2BGhwU0w9q1nCH0teLiDI3UI%2BssItq3rLs4eQtd%2B6OlqK3e%2B38bRjkhXCvDddng7FlGPWNU9c08KccvahAdmjF3iZUs%2Bytjt2pMbLf%2B2m7RTJCu-D%2Bv9capRrCAxskDA0wNTKg40SDzoWjH3E-BrIFmrN9RXVwz8t4VPmS4ehvxWwtSTpwxtaVqHlTXm0RRpdN7qPqXjvojWjHVntJ8zWrRaxW4dwPStXjoaz2CbVsJ-tMpb3mYfZJi5r7ZMmPk1%2BsJDi-Nxf-aGX9CqANaZ7f5ezoVlGVaM3rEzxFLNwdy3enLHG0FIftC2PjGa0jOdBRhtzY2p0zVtYuXhpHvHfgfTN8d7mQvSoMUObdCnuNBK1sksV3rqHiKS8kFLAmhxCb7VUm9YmrO5ZFVJ90c5S0fpq84w9Q3tOLbvGpmrmnSNGkWYnZrhnN7tZgz1%2B7nXet7tWwKObDjvtVvsWNxT8OW2bUGiQk4iLZCgLQAAD3YjS0kf8KSAOpSAhkolSWMrZDJTk8keRKRyLulNw4AeyaI4a0ytqGi9BNMdkj4Zho%2BTPNK6Eo1PVi%2ByWxoXMmOkhJKW%2B4wh5ShuN0maumbizGS%2B1YzBe-OZVyoqg5hYJ8aJnxQEgEQlBSdXxvnfFAj9iAAGp%2BD31tzAElDL-48Qp1SQSdI6W079-wJljPYFsqUhy-aGt%2BPaFs-y6XbGzVfrslamcAQr2ej%2BBV1TlpfXAn9eswNpd9I6ZDsvBPyrWO91Xvtk1MKT119TfsAvBMi8nhT8asv8TSJ-tb33pe3PI0nGjQ68O8bu4pIhud0fDXaukezXKYvvewoy7Nfh1xYLR0T-ly8V8zq9NgpyDvtVe%2B6gHhnzUuf0H9Q6Bb5yqG7bmydsf%2BQi-dRdK58vGUj-J-NZdcTDaFYRAjaWFVUhPHEAN3eiFiElZQLgYlDiclf%2BKlYPWlGncBCSCPBnGBVlFnZSLoJYVPWVbXJJUXH4aVAjZpKrQZTLAXVVR1dQLmV7YFINfkV-ebA9VUHrImaqVVUrI9NrHQJVexePUMCUIcf1TnOtesdfKiJtCFcwZQmAuA5iViOnf3cnSlSnTAkAYSelCBPA6BFlZneBZDb5GEGAvgQgFAYBYgR3TFZ3V3UADQhA7QtAwPIBUnIwsPEwqSZlJnOBdlRrJmECfIRFM%2BCAfAJAQlfAMAEgagUnAPPQoPRwrAsBbQ0w4I6PIg5LK6IJTgk8FbexUZK-QeKZRZSKBWXeS0NfUo3Dco5mK9PuCo0wXTejcyPQe6ZQgUMo8yCokdRvaoq4XVBCMLexUYRWPOaaBUJxbaX2eov5bII9YvQYioVo5fY6DsOo%2B6KYno7IWYx0eYlpU43Meo%2ByVY9QdYpoiGLY3uNo%2B4DokQ0VMmYcVgy0WY0wOOUMX4yOG4oiUwSIKRG4u4rKTYlwYY546EjaTONuQ4%2BzL4uo%2ByAEi4yOBEoE2sEEkec4iErUKE3Y8iWE4ky0IwA47o5EjwVE3ov4ozWY7E-4k2fE7vSE5ooYiGKmUg5sGaCY948A44q47aBYuYy4zo1k-ovMDkx4tqEgjMPYmkyYqkjYL4nmEU844Emk7cJxAkgYmUuE2abkhU1Qt4jbQUlEmkt4QsHEw8RYnEozZ5NYtkwkg0skmGQxI1Jff2Skj4mY7ecksUgMnmUUjEmOQM8El0-Uh4w0uUz0gpRUxElUvPGkq04U20zUh0wE3UqM6UmM90gieMmvCU30i01M%2BohEjE-2EMzM-4uUesHMqU6dMZMYu1MjJ4YzaQVBcxMyaTSvI7Ks9NEfevMZI5d1SxPMIiTQDXJ2OE8IFjf4ObMcyvCcrssIVJOyIiONRHHwKwOVQZcQcwcIF8Sc2scQedL5cVEIDE7shoCFXc28LmIiQ8sFA9DMcsSeHQFjUXcQzdfKG04-NczcYJRoRcWhasU8wC9GMyHwdMM8p9OocjBTLc4IKwiZYDNef4fhLs0yQbL9PRTlRCmUZac3VsIzDYt01sojds3kqXZvEITs8IPZNybC%2Bc9eEIfC0VSgoaWETsLnHjfVSHLIIWHhICZi7Cr4vvT0zGNjXDW5bPNyEivuIsmISkkLNRHMkorKQok1YowfeOIk1skYqoion05Uv0oU9Uk6UMpYlYxs4vPMkisk4y9o%2BEpUgU6YyygC602s8Uu050psxylsmEnY1sks8yss9Ms4pk8Up0243M6Mpyoy0ksK1rDyo4tU7yuyoM-YyqeygyyikK-ijoikiKzyzKoM64%2B0-4nyyMwK5s4RCoufO8p4PkpMiyiqqsmynEpxUMvUtWQypq%2B5Fq2i749qyKqy6K6qozFkuqhyhqloo0psHkmxU08a8qk4jUmKhoiM-KrKIS4mCAn5CNLg9dSg-COJJSg6ICApNS1aOEpsg6szWMI6%2B8x9aKFKrPGCrjA7Z2DNOZfvA4kWIRNUwq7Y4q%2BEh0fq-6z6OJIGv-dsP6pKoa401q8YgK9feVIRRXKse6HmeWVQktF4R6k3DcoGaTL0xra5SY4G6-SysGxZedH8jG6KVePuMm3uc6iAy8eG%2B60G-MqiwsmQmvasvUg6rmPIdS4GhG9uBGbGMZC7K5M0g-dvFqkmxfNwUgxZZihjDNbTI4IG1URqBKx2BmNuAE41Ug-o8WkC2WvlF9QFM5JRKtPG5Yy2nrWk6cK2hyz6lHb6t8xtPWVQ9KeENEozaG%2BSi6tyIG66uU6G5qlauyOCw6biyUOtLNSMIG9cg7CO7mzURuW2Fix2waMxV2%2Bo92k2%2BW4WJeJWpM-TEHGvL5KO1yo%2BUbWxPW%2BrLohuoefSoaCm7tJrF2hCas5IUiD22YiuwK32mTf28RbtQ2ocGkhyrmwVREyGRpOOk24axOoGEO1O1CfWzOmm7O8MASj61ep2y6pNZpUKUu4et20sb2nvKu91Guyoam0Veu2cueV85ul4yiUwGAz%2BNAGAFAKAZI9FJ3bFd3eArQv3bw9I3w6nbI8PIIqPQgywwbSI8rWIaIpFagEBuABACAB3DFLFF3EkDwuBiBBBvifQzIww0PHA%2BnMwkImPVQHcr7b%2Bw7PBq3WQagGAPgOAYkJwsh1w7ifFcB8gHEYh2hgBDIvwphnItBggiwtQZ8FoR8QobBDwHfcINwfkeoGoDwExhwIwY8rs4xPQc86QUxiW2xhxjeLMRxhxjRhwLRrBfQcwNxyGNwTxhoSIOx7DfQXRlMdcYIIJnxjxtBJwDwKJvxmJ1x6DaJnQWJ6QeJhwTxoWOJ5JhJnQcwHJzRvJ7J9J3JzJtBAp0pop8p-JpJ6p7R1Jup9x4ptJi0aQjJhplIIJq8mxnfRcQp5pmpjpzx4ZxJnIUZtkkWCZ6ZxoSIeoSIfRlxhGdYZDfxx4Uxy8CZjZpwCZ%2BwCZ9QKwHZwJlxiZixjcTQcwaQlq6Zsphpm5%2Bp-xuZ25zx%2BydYCZx8NXKpwZu5554ILZr53xmpt535gFlJiZiUo5e575-xowKFwFzp2FvQcF2Zl8Pc4UeoCCUzbxkFuFsFkF7s3FvJ%2BoSUUiUoWFnFvZkFkWbFh5v5kFqwRoeoax5lzwPcxl0J0FvJ6JTloFjFnlhpp52lqKQlmpuRcFklpp%2BFkZ1QypiZ8QE5AZqVuloVkVhpg57ICkwV6FirJwZDcM6ZyllVnF9%2BxVlJx4VV-x4l-ltZ9sclo1%2B17VhwHZ-FvMF8cs7snBJ8CFcxrVpV615Vx1z0C1gNv1wuCYW80E1Q2ZtwdJiyAwQ1x13ZyvZ1h1v13UCZvBS0GlwNjmBwNilcA1w5u1xNqlscn0Xi3NXZkVDsYN-1kIJNhN0NkF6UUwDkyIK50gl82totRlnFql%2BVKtxtlJ%2BKjcKibtyFkFsYWtuouNQuSoVY2txcfZ1eSNbQZDOVrMF2XZqZUXWOHQYtv19V2t49gwOIfsJtM8QuFoK0NpbNptoV6rf5oJs51CkhJFkF6ckwbQUZvB-hv3JI8gPACAEnORjAhh-w5hyBfA8w0IpSDfJm01WsZpM25q--FW-2%2BVKCsmKvCxcWYi78pZUaKmS8BvH6yIhQqM%2BIJxN4B9ESsEZcmSrSw1UvLfIUuNOj6edC4a5wCWOE%2BpBTUeL89innM4DraaFVJuYTlcpD7i-UD8Kteg96-andwafNJTwQtnFRful1WpEjoc8RCVY7LGaIX5JUAoOoFNfvSI-nSvKfbnHGVqQ-U%2Bnzd8x4DE%2BxHwSVboq2MKVQ0YJxSWaZa4TjgGvYGYWuQcdpbO-zcbQFFD4avT1CVmCXdDuJXcLT0DYWBpDuTTvDToB7QXMjtDx8xz%2B1A7FzgfL0Gzk%2B2Xd1CzsgxDimfg-vINQr8sA5S2EcPCZr7NStDrs9AIIpeTwyGS0XROI28rkr3kgigoTJG4ZSozors1D01XOL%2Br1Dm-HLgL%2BCocLzxzCtGUK0XLupVT0EEL6vdUUoPJN1CuQb-D57KWxmGXY3BDvRI1Kz2Gbh17l4TVUKXrgDbm26dLoZdbhLoKcLoTNboj83G5KHvvYjxG50-a56pQwS1GFa77yArHRjFmavRJYTmVQ1Ck%2B4GAjgWAViSkIDkD4gNIuhhR5B4w3AlRmD9h%2BDi%2B2r4NMz8xSmIcD5YVF7pzzDzFxp91BNZqnj%2B7k7n4D7ROc0H1NzOizfNPd66VVGQn-TE5P0U%2B%2BTx2INAXsrsuQC8ZTenNNH5asITH2riLlxXH3D1XrbbhzXgnnXkESSkVfai7Pyb6JCm5XijC3DimPntUgIfkXOeKtQq3IAA)

**Comment by Posandu** [comment]
Oh, Thanks @NatumanyaGuy. I'll look into it. In the meantime, you can add the class `ripple-effect` to those affecting elements.

**Comment by NatumanyaGuy** [comment]
Thanks a lot.

**Comment by Posandu** [comment]
Hey, @OfficialCRUGG and @NatumanyaGuy
I just published version [1.0.5](https://github.com/Posandu/svelte-ripple-action/commit/6ca515f8347ac0e3dc3acaa2632806c540eeeaac) which fixes the issue. Previously it was adding a class which was causing the issue. Now, it adds a custom attribute instead.

**Comment by NatumanyaGuy** [comment]
Thanks a lot!
