### ISSUE TITLE
Ripple not big enough (when clicking on right side of element)

### ISSUE THREAD

**Issue by OfficialCRUGG** [Tronic247/svelte-ripple-action#4]
Across all instances where I use the ripple effect in my app, the ripple is not big enough when clicking on the right side of an element, whilst the size is okay when clicking more on the left. See the attached video:

https://github.com/Tronic247/svelte-ripple-action/assets/25248999/eb4711f1-5dd3-4e18-9bab-12fc5a78e5d9

This occurs on both latest Firefox Stable as well as Chrome.

**Comment by OfficialCRUGG** [comment]
Was also able to reproduce the same issue in another separate project, freshly created.
If you cannot easily get this reproduced, here's some more exact instructions:
- Use `pnpm create svelte` to create a SvelteKit app.
- [Set up UnoCSS](https://unocss.dev/integrations/vite) and also import "@unocss/reset/tailwind.css" from `@unocss/reset`.
- Create an `<a>` element with the ripple action. Try a few different sizes and widths, and with some, this should occur.

**Comment by Posandu** [comment]
~~Hey @OfficialCRUGG thanks for the issue and the steps to reproduce it. I'm currently having some exams so I'm unable to push any fixes until they're finished. I'll look into this after that. Thanks again!~~

**Comment by Posandu** [comment]
I just tried to recreate the above issue using the conditions you mentioned. 

https://stackblitz.com/edit/sveltejs-kit-template-default-j7jbxd?file=src%2Froutes%2F%2Bpage.svelte

But there isn't the issue that you're getting 🤔

**Comment by OfficialCRUGG** [comment]
I'll try to set up a repro example the next few days

**Comment by Posandu** [comment]
Hey! I assume you've found a fix and this library is working correctly. Feel free to reopen this issue if it still persists.
