### ISSUE TITLE
Update to support Svelte 5

### ISSUE THREAD

**Issue by kennyhei** [Tronic247/svelte-ripple-action#5]
First of all, great library 👏 

However, npm install gives me error

```bash
npm ERR! Found: svelte@5.1.12
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^5.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^4.0.0" from svelte-ripple-action@1.0.6
npm ERR! node_modules/svelte-ripple-action
npm ERR!   svelte-ripple-action@"*" from the root project
```

Looking at the project source code, most likely it will work out-of-the-box in Svelte 5 so adding the support in `peerDependencies` would be greatly appreciated!

**Comment by Posandu** [comment]
Thanks for the feedback 🤗

I just published v2.0.0 and it should work now
